### PR TITLE
Unify scripts for building & deploying

### PR DESCRIPTION
**Pull request by Xerus2000**
Now, instead of a bunch of weird shell scripts, there's one tool I created and called docs. I'll explain each of its commands with another help command tomorrow, but it basically does what all the scripts did plus allow you to easily get started with the project.

### CODE REVIEW

**Comment by SKoschnicke** [comment]
Although it's work in progress, I have two suggestions:
- put the source of the commit hook into a separate file. Source code inside other source code has some disadvantages
- when writing shell scripts, check them with shellcheck https://www.shellcheck.net/

**Comment by Xerus2000** [comment]
- I like to reduce clutter, which means no files laying around somewhere. Where would you put this file, since no one has to interact with it?
 - I'll make sure to check it soon

**Comment by SKoschnicke** [comment]
I would put it into a directory `git-hooks`. It is a normal git hook, which is useful even without the `docs` script. See also https://stackoverflow.com/questions/3462955/putting-git-hooks-into-repository

**Comment by Xerus2000** [comment]
should be finished now. running `./docs` with no or wrong arguments outputs this:
```
Usage: docs <command> [options]
    setup - install the gems required for generate and setup the post-commit-hook
      └─ live - also install the gems required for a live-preview
    generate - copiy the images and convert the adoc to html
      └─ pdf - also convert to pdf
    publish - refresh the last update date in the header of the docs and commits
    update-date - update the date in the header of the docs to the date of the last commit
```

**Pull request merged**
